apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: partner-catalog-hxsg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: partner-catalog-hxsg
    app.kubernetes.io/part-of: partner-catalog-2
  name: partner-catalog-hxsg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: partner-catalog-hxsg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: partner-catalog-hxsg
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ergonzale-tenant/partner-catalog-2/partner-catalog-hxsg@sha256:fc855f30e40019256e5c553d30ff13049f7ad046f6d601d7dc71bee6aa8506ef
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
